tap "alienator88/cask"
tap "espanso/espanso"
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "martido/graph"
tap "shivammathur/extensions"
tap "shivammathur/php"

brew "cask"

## GNU Project
brew "binutils"
brew "coreutils"
brew "findutils"
brew "inetutils"
brew "gnutls"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnupg"

## Commands
brew "bat" 
brew "cliclick"
brew "cloc"
brew "cmatrix"
brew "dust"
brew "eza"
brew "htop"

## Web Development
brew "httpd", restart_service: :changed
brew "php", restart_service: :changed
brew "mysql", restart_service: :changed
brew "memcached", restart_service: :changed
brew "composer"
brew "hugo"

## Comand Line
brew "grep"
brew "openssl@3"
brew "fastfetch"
brew "fortune"
brew "fzf"
brew "rsync"
brew "rust"
brew "shellcheck"
brew "smartmontools"
brew "starship"
brew "tailwindcss"
brew "tealdeer"
brew "thefuck"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"
brew "imagemagick"
brew "lolcat"
brew "mas"
brew "micro"
brew "navi"
brew "nmap"

## Development
brew "node"
brew "pandoc"
brew "php@8.1"
brew "php@8.2"
brew "prettier"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "shivammathur/extensions/imap@8.4"
brew "gh"
brew "git"
brew "go"

## Browsers
cask "zen-browser"
cask "firefox"
cask "brave-browser"

## Social
cask "discord"

## Quicklook
cask "quicklook-csv"
cask "quicklook-json"
cask "webpquicklook"
cask "qlmarkdown"

## Media
cask "affinity-photo"
cask "nzbget"
cask "vlc"
cask "imageoptim"
brew "nzbget", link: false

## System
cask "alt-tab"
cask "applite"
cask "backblaze"
cask "betterdisplay"
cask "bitwarden"
cask "jordanbaird-ice"
cask "keka"
cask "keyclu"
cask "logi-options+"
cask "lookaway"
cask "maccy"
cask "hyperkey"
cask "chatgpt"
cask "iterm2"
cask "malwarebytes"
cask "mission-control-plus"
cask "parsec"
cask "pearcleaner"
cask "raycast"
cask "synologyassistant"
cask "timemachineeditor"

## Development
cask "github"
cask "vscodium"
cask "zed"
cask "obsidian"

# Fonts
cask "font-poppins"
cask "font-daddy-time-mono-nerd-font"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-meslo-lg-nerd-font"